- src/line.js
> When using a dashed line, make sure to save and restore the canvas

- README.md
- samples/bar.html
- samples/bubble.html
- samples/combo-bar-line.html
- samples/line-logarithmic.html
- samples/line-time-scale.html
- samples/pie.html
- samples/polar-area.html
- samples/radar.html
- src/annotation.js
- src/helpers.js
- src/index.js
Check Scales on ChartOptions to avoid null errors.
Fixes #49
> Annotation plugin improvements (Fixes #3, #35, #47, #49, #51, #53, #63, #66, and #68)

- src/types/line.js
> Bind events to line labels

- README.md
- samples/bar.html
- samples/combo-bar-line.html
- samples/line-logarithmic.html
- src/annotation.js
- src/helpers.js
> Allow overriding `drawTime` per-annotation

- src/annotation.js
- src/element.js
- src/events.js
- src/helpers.js
- src/index.js
- src/types/box.js
- src/types/line.js
These are fixes suggested by eslint. There was too much to make all the changes and enable eslint all in one PR. Will send a separate PR to enable eslint
The `case` statement formatting seems potentially funny to me, but otherwise the style rules it suggested make sense
> eslint fixes

- .gitignore
- src/events.js
- src/helpers.js
Avoid 'Unable to preventDefault inside passive event listener invocation.' message.
Support compatibility with old browsers
Closes https://github.com/chartjs/chartjs-plugin-annotation/issues/159 https://github.com/chartjs/chartjs-plugin-annotation/pull/122
> fixed prevent default

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
* Add release-drafter
* Run on v2 branch too
> Add release-drafter (#233)

- samples/animation.html
- samples/bar.html
- samples/box.html
- samples/bubble.html
- samples/combo-bar-line.html
- samples/horizontal-line.html
- samples/labels.html
- samples/line-logarithmic.html
- samples/line-time-scale.html
- samples/pie.html
- samples/polar-area.html
- samples/radar.html
- samples/updates.html
- src/annotation.js
- src/events.js
- moving output to `dist` was not applied to samples
- `chartInstance` was missing from elements
- use `draw` instead of `update`.
- remove calls to `event.preventDefault()`
> Fix some issues detected by inspecting samples

- src/annotation.js
https://github.com/chartjs/Chart.js/pull/7949
> Reflect IPlugin changes from Chart.js

- .editorconfig
- README.md
- samples/animation.html
- samples/bar.html
- samples/box.html
- samples/bubble.html
- samples/combo-bar-line.html
- samples/horizontal-line.html
- samples/labels.html
- samples/line-logarithmic.html
- samples/line-time-scale.html
- samples/pie.html
- samples/polar-area.html
- samples/radar.html
- src/annotation.js
- src/events.js
- v3-migration.md
> Align event hooks with to datalabels plugin

- README.md
- samples/bar.html
- src/annotation.js
> Add context to display callback (#255)

- package-lock.json
- package.json
- types/element.d.ts
- types/events.d.ts
- types/index.d.ts
- types/label.d.ts
- types/options.d.ts
- types/test/exports.ts
- types/test/tsconfig.json
Requires: https://github.com/chartjs/Chart.js/pull/8048
Closes: https://github.com/chartjs/Chart.js/issues/7945
> Add initial types

- src/annotation.js
> Add returns elements in `resyncElements` 

- src/annotation.js
> Enables display options (#289)

- .editorconfig
- karma.conf.js
- package-lock.json
- package.json
- rollup.config.js
- samples/.eslintrc.yml
- src/annotation.js
- src/events.js
- src/helpers.js
- src/types/box.js
- src/types/ellipse.js
- src/types/line.js
- src/types/point.js
> Update dependencies and version to 1.0.0-beta

- package-lock.json
- package.json
Add types ref and prepare next beta
> Add types to package.json

- src/annotation.js
- test/index.js
- test/specs/display.spec.js
> Initialize always all elements even if do not show 

- README.md
- src/annotation.js
Added beforeDraw drawTime hook to fix the gridline issue described in #251
> beforeDraw hook added

- types/options.d.ts
'beforeDraw' added to DrawTime type (#303)
> types modified to support beforeDraw hook

- src/events.js
- test/specs/events.spec.js
> Ignores no-display elements during events management

- package-lock.json
- package.json
- samples/updates.html
- src/annotation.js
- src/events.js
- src/types/box.js
- src/types/ellipse.js
- src/types/line.js
- src/types/point.js
- test/specs/point.spec.js
- types/index.d.ts
- types/options.d.ts
Closes: #265
[(outdated) demo](https://codepen.io/kurkle/pen/rNWOdNG)
> Chart.js beta.13 compatibility

- .github/workflows/documentation.yml
Noticed this failed in https://github.com/chartjs/chartjs-plugin-annotation/actions/runs/651452688
> Fix documentation GitHub actions

- README.md
- package.json
* Adds documentation badge
* Adds awesome badge
See it in action at https://github.com/etimberg/chartjs-plugin-annotation/tree/add-docs-to-readme
> Add badges to readme

- README.md
text of the url sugested the docs for the main lib, update text to represent url of the plugin docs.
> Update url text

- docs/docusaurus.config.js
> Link to samples from sub pages

- .github/workflows/documentation.yml
- docs/guide/options.md
- docs/guide/types/box.md
- docs/guide/types/ellipse.md
- docs/guide/types/line.md
- docs/guide/types/point.md
- docs/guide/usage.md
+ disable autocolors in guide sniplets
> Switch deploy action for preserving history

- docs/scripts/register.js
- karma.conf.js
- package-lock.json
- package.json
- rollup.config.js
- src/annotation.js
> Add version information to charts in documentation

- docs/.vuepress/config.js
- docs/samples/types/point.md
https://16ccc8d7.chartjs-plugin-annotation.pages.dev/chartjs-plugin-annotation/samples/types/point.html
> Add point example

- docs/.vuepress/config.js
- docs/samples/charts/bar.md
> Add sample on bar chart

- src/annotation.js
- types/label.d.ts
- types/options.d.ts
- types/tests/exports.ts
> Update option typings, fix `type`

- src/types/line.js
> Restrict mouse events to where the line actually is

- rollup.config.js
> Remove sourcemap

- docs/guide/index.md
> Add warning about registration to Getting Started

- docs/guide/types/box.md
- docs/guide/types/ellipse.md
- docs/guide/types/line.md
- docs/guide/types/point.md
- src/annotation.js
- src/types/box.js
- src/types/ellipse.js
- src/types/line.js
- src/types/point.js
> Add adjustScaleRange options

- README.md
- docs/.vuepress/config.js
- docs/samples/.eslintrc.yml
- docs/samples/intro.md
> Move readme example from codepen to docs

- docs/guide/types/box.md
- docs/guide/types/ellipse.md
- docs/guide/types/line.md
- docs/guide/types/point.md
Can provide strings to define points for example to target labels: https://jsfiddle.net/Leelenaleee/xqLz0g35/16/
> Update types of config

- types/label.d.ts
> LabelOptions.width and .height are optional

- docs/.vuepress/config.js
- docs/samples/charts/line.md
- src/types/line.js
> Hide line-annotations completely outside chartArea

- types/index.d.ts
ts typings for https://github.com/chartjs/chartjs-plugin-annotation/issues/470
> Typings for default settings on element

- docs/guide/types/point.md
Fixes point annotation documentation
> Fix the point annotation documentation guide

- types/options.d.ts
> Fix type for CoreAnnotationOptions.borderDash

- .github/workflows/npmpublish.yml
> Fix syntax error from previous commit

- .github/workflows/documentation.yml
- .github/workflows/npmpublish.yml
- docs/.vuepress/config.js
- package-lock.json
- package.json
- scripts/docs-config.sh
If I did not make any mistakes, this should publish the docs in `master` / `latest` / `next` / `x.x.x` sub folder.
We need a redirect to the latest folder. And we need to generate docs for releases.
> Documentation versioning

- docs/guide/types/line.md
- types/label.d.ts
> Add border* options documentation and types for the label in the line annotation

- README.md
> Fix broken 'View this example' link

- docs/guide/types/line.md
> Fix line annotation documentation

- README.md
> Updates README with new features

- docs/guide/configuration.md
> Add note about clip option usage and events catching

- docs/guide/configuration.md
- types/options.d.ts
> Fix `animations` option type and add missing documentation

- package-lock.json
- package.json
> Bump version to 1.2.0, update dependencies

- test/fixtures/label/positionHorizontalPercentage.js
- test/fixtures/label/positionVerticalPercentage.js
- test/fixtures/point/adjust.js
- test/fixtures/point/boxLocationAdjust.js
- test/fixtures/polygon/adjust.js
- test/fixtures/polygon/boxLocationAdjust.js
Removes point nodes from label annotations in the test cases
> Remove point nodes from label annotations in the test cases

- .github/workflows/npmpublish.yml
Previous attempt was flawed, this could actually work.
> Publish latest/next docs in separate job

- src/events.js
- test/events.js
> Remove undefined event listeners from state if disabled at runtime

- src/types/ellipse.js
- test/specs/ellipse.spec.js
> Fix events catching on rotated ellipse annotations

- src/types/line.js
- test/specs/line.spec.js
> Properly consider the line thickness in the intersect calculation

- src/types/line.js
- test/specs/line.spec.js
Fix #602
Adds additional test cases
> Fixes events triggering on the label of a line annotation

- docs/samples/line/labelVisibility.md
I wanted to capture some of the discussion from #589 for other users' benefit.
I also removed some properties that were using their default values in order to make the example more focused.
Feedback welcome, and if this isn't the style of example that you want, feel free to ignore.
> Update labelVisibility sample to demonstrate different approaches

- test/specs/ellipse.spec.js
This PR is adding test cases with ellipse with radius 0 and with an undefined rotation.
> Add specific test cases for ellipse annotation event handling

- test/events.js
- test/fixtures/box/label-dynamic.js
- test/fixtures/line/arrowHeadsDeleteAtRuntime.js
- test/fixtures/line/label-dynamic-hide.js
- test/fixtures/line/label-dynamic-show.js
- test/index.js
- test/specs/box.spec.js
- test/specs/ellipse.spec.js
- test/utils.js
Ref: https://github.com/chartjs/chartjs-plugin-annotation/pull/634#discussion_r786623952
> Tests: use helper function to fetch elements

- test/fixtures/label/contentMultiline.js
This PR adds label fixture to test missing and empty content
> Add tests for missing and empty label content

- test/specs/label.spec.js
This PR remove events test cases with `inRange` method tests.
> Label: change event tests to inRange tests

- docs/.vuepress/config.js
- docs/samples/box/canvas.md
- docs/samples/box/image.md
- docs/samples/label/canvas.md
- docs/samples/label/image.md
- docs/samples/line/canvas.md
- docs/samples/line/image.md
- docs/samples/utils.md
- docs/scripts/utils.js
> Add samples of image and canvas as label content

- src/helpers/helpers.canvas.js
> Fix the usage where jsDOM is not present

- docs/guide/types/line.md
Fix wrong sentence in the line annotation documentation
> Fix wrong sentence in the line annotation documentation

- docs/guide/configuration.md
- docs/samples/line/labelVisibility.md
- src/annotation.js
- src/events.js
- test/fixtures/box/label-dynamic.js
- test/fixtures/line/arrowHeadsDeleteAtRuntime.js
- test/fixtures/line/label-dynamic-hide.js
- test/fixtures/line/label-dynamic-show.js
- types/events.d.ts
> Enable event handlers to indicate chart should be re-drawn

- docs/scripts/defaults.js
> Change default interaction options in chart defaults for the samples

- docs/guide/migrationV2.md
- src/types/label.js
- src/types/line.js
> Reduce visibility of some line annotation element methods

- README.md
> Update min version req in readme

- test/fixtures/line/labelsScriptableOptions.js
- test/fixtures/line/scriptableOptions.js
- test/fixtures/polygon/hexagonWithPoints.js
Change tests configuration using new 'common' plugin option
> Change tests configuration using new 'common' plugin option

- types/options.d.ts
Add point option to polygon annotation options type
> Add point option to polygon annotation options type

- src/types/label.js
Improve usage of rotation option in callout management
> Improve usage of rotation option in callout management

- test/specs/annotation.spec.js
Use getAnnotationElements utility where not used in the test cases
> Use getAnnotationElements utility where not used in the test cases

- docs/scripts/register.js
- package-lock.json
- package.json
> Remove autocolors plugin from doc going to Chart.js color plugin

- docs/.vuepress/config.js
- docs/samples/label/autoscaling.md
This is PR is adding a sample how to scale the label fonts when the chart is resizing
> Add sample for label auto scaling during chart resize

- types/label.d.ts
- types/tests/exports.ts
> Fix font type definition to be partial

- package-lock.json
- package.json
> Bump to version 3.0.1

- package-lock.json
- package.json
- test/fixtures/label/contentMultiline.js
Release new version with enhancements and bugfixes
> Bump package to 3.1.0
