README.md

I couldn't figure out why my box was as tall as the scale, even though I set `yMin` and `yMax`.

Typo in box example

---

README.md
samples/box.html
samples/horizontal-line.html
samples/labels.html
src/element.js
src/helpers.js
src/plugin.js
src/types/box.js
src/types/line.js

Add an array of the events that should be watched to the `annotation` config object, and a corresponding `on{Event}` function to each annotation. Event callbacks are passed the event object as the first argument, and the target element is bound to `this`.

Support mouse events on annotations

---

README.md
samples/horizontal-line.html
src/element.js
src/events.js
src/helpers.js
src/plugin.js
src/types/box.js
src/types/line.js

Also fixes a click event duplication when a `dblclick` event happens.

Support hover events

---

src/types/box.js

Otherwise, the plugin cannot be bundled with 'use strict'

Declare variables to comply to 'use strict'

---

src/types/box.js

You can see the issue here: https://codepen.io/anon/pen/EvggZy.
Basically when creating an annotation like this:
```
{
drawTime: "beforeDatasetsDraw",
type: "box",
yScaleID: "y-axis-0",
yMin: 0,
// yMax: -10, <------ uncomment this to make it work!
backgroundColor: "rgba(101, 33, 171, 0.5)",
}
```
without specifying for example the `yMax` parameter, it throws an error on missing chartInstance object. I understand that there may be another problem why chartInstance is missing but this fixes the error and makes it work.
PS: I've already merged PR #65 in this one but needed to update the code position. Thanks

Fix error on creating box annotation with missing min or max param

---

src/annotation.js

Chart.js has a [`render`](https://www.chartjs.org/docs/latest/developers/api.html#renderconfig) function in addition to `update`. Unlike `update`, calling `render` does not recalculate the layout and update datasets, so it is far more performant in cases where only config or plugins have to be updated. However, `render` does not invoke the `afterScaleUpdate` hook, so calling `render` with an updated annotation config will not update the annotation, since `element.configure()` takes place in the `afterScaleUpdate` hook. 
To remedy this, I've moved the `element.configure()` call to within the draw function, so that it still gets called when `render` is called. This means that, in scenarios when only annotations need to be updated, we can now call `render` instead of `update` for a …

move configure step to draw time, to support render call

---

src/annotation.js

Added PLUGIN ID 'annotation" in order to register into Chart.js as required like best practise.
In this way you could disable in some chart instances, if you want

Added PLUGIN ID because missing

---

gulpfile.js

Building the project, you get an error because "preserveComments" is not longer supported (see [here](https://github.com/terinjokes/gulp-uglify/releases/tag/v3.0.0)).
Added tag @preserver and new gulp-uglify option to support to maintain the header into minify file

"preserveComments" no longer available on gulp-uglify

---

chartjs-plugin-annotation.js

Happens when unregistering plugin in Angular on production build

Fixed "Cannot read property 'onDestroy' of undefined"

---

README.md
samples/bar.html
src/types/line.js

Hi,
I added a parameter `rotate` for line labels. As it is named, this parameter allows to rotate the label. I needed this feature to display the label of a vertical line along the line (ie the label is vertical too).
I updated the sample _bar_ to add a demo of this feature.

Add rotation option for line labels

---

src/annotation.js

JS Maps use `delete`, not `remove`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete
The code mistakenly used beforeDatasetDraw (singular), which caused the annotations to be drawn for every dataset, instead of being drawn once before all datasets.

Fix destroying annotations and beforeDatasetsDraw

---

samples/bar.html
src/annotation.js
src/types/box.js
src/types/line.js

Fixes #244.
Adds display property to the annotation element options (both box and line). The default is `true`.
```javascript
plugins: {
annotation: {
annotations: [{
type: 'line',
display: false,  // <-- new option, default is true
scaleID: 'y',
value: 10
}]
}
}
```
It can also set by a callback in order to hide the annotation using a logic related to chart or datasets status.
```javascript
plugins: {
annotation: {
annotations: [{
type: 'line',
display(chart, options) {
// your logic, for instance the annoatation is shown 
// only if a dataset (in this case the first one) is not hidden
return chart.isDatasetVisible(0);
},
scaleID: 'y',
value: 10
}]
}
}
```

`display` setting for annotation

---

README.md
samples/animation.html
samples/bar.html
samples/box.html
samples/bubble.html
samples/combo-bar-line.html
samples/horizontal-line.html
samples/labels.html
samples/line-logarithmic.html
samples/line-time-scale.html
samples/pie.html
samples/polar-area.html
samples/radar.html
samples/updates.html
src/annotation.js

Fixes #247 and #249
The annotations node of setting is not longer an array  but now all annotations are managed as properties of an object where their key is their ID as well.

Remove annotations array, using an object instead and min/max on value and endValue options

---

src/annotation.js
src/events.js

This fixes a few mistakes I found:
* Fix moveListened vs. listened: If a chart's only hooks were move hooks on individual annotations, then when the chart is updated, `state.listened` was cleared at the beginning of `updateListeners`, but since `state.moveListened` was still set, the `annotations.forEach` loop didn't re-evaluate move listeners and re-set `state.listened`.
* Update plugin hooks for the [new IPlugin interface](https://www.chartjs.org/docs/master/getting-started/v3-migration#iplugin-interface): This fixes problems with `handleEvent` not seeing the correct event type and with the drawTime option not being honored.
* Fix ESLint warnings: ESLint was giving a [no-invalid-this](https://eslint.org/docs/rules/no-invalid-this) warning. The annotations.display callback isn't …

Various fixes

---

README.md
src/annotation.js
src/helpers.js
src/types/box.js
src/types/line.js
types/label.d.ts

Implementation notes:
Since not all annotation types implement labels, the `drawLabel` method is optional.
If the `labelDrawTime` option isn't specified, then it checks the individual annotation's `drawTime` option, then the chart-wide annotation plugin's `labelDrawTime` option, then the chart-wide annotation plugin's `drawTime` option. This means that you can't override an individual annotation's `drawTime` without also affecting its `labelDrawTime`, but I think it's the more intuitive and backward-compatible behavior.
Since the option should default to `drawTime` if not set, I did not add it to the `defaults` object. Please let me know if I've misunderstood how plugins' default options should be implemented.

Implement a separate labelDrawTime option

---

types/options.d.ts

Fix PointAnnotationOptions

---

types/index.d.ts

This allows types to be consistently imported and augmented from `'chartjs-plugin-annotation'` without needing to understand the internal organization of types. See discussions under #296.

Consistently export all types

---

src/annotation.js
src/index.esm.js
src/index.js
types/index.d.ts
types/test/exports.ts
v3-migration.md

Annotation types are not really designed to be shakeable, so it makes sense to automatically register them as elements when the plugin is registered.
This is one step towards removing the automatic registration from `UMD` build, for consistency.

Auto register/unregister annotation types

---

karma.conf.js
package-lock.json
package.json

karma v6 refuses any arguments it does not support, so removed the `--grep` and `--coverage`. Coverage is now handled through `NODE_ENV`, grep is not really needed in this project, because we don't have many tests.

Update deps, bump version

---

README.md
src/types/line.js
types/label.d.ts

Fixes #314
Moves `color` options out from `font` object in order to be aligned with Chart,js configuration.

Moves color option out of font namespace

---

src/annotation.js
src/helpers.js

The `adjustScaleRange` method, which is calculating and adjusting the min and max values of a scale based on values of annotations, is evaluating the annotations values taking the options from elements in the state.
Elements are created/updated after the `adjustScaleRange` method therefore the method should not use elements. In this PR the method is using the options. 
Setting the min and max values for a category scale doesn't make sense because the value of annotation should be in the configured labels of the chart.

Adjust scale range method using options instead of elements

---

README.md
samples/point.html
src/annotation.js
src/types/box.js
src/types/ellipse.js
src/types/line.js
test/specs/point.spec.js

Applies element defaults before resolving element properties

---

src/annotation.js

The animation resolution was broken after https://github.com/chartjs/Chart.js/pull/8332, this fixes it.

Use the new isolated key for animations

---

src/annotation.js
src/types/line.js

Results to this:
Instead of this:
And prevents this:
Reproduce of the above error, hit randomize data couple of times there (and inspect console):
https://www.chartjs.org/chartjs-plugin-annotation/samples/types/line.html

Resolve element options to concrete values

---

.github/workflows/documentation.yml

The docs are not working after migrating to vuepress-template-chartjs, its suspected that too old node version could be the cause.

Use node 14 to build docs

---

docs/guide/options.md
types/events.d.ts
types/index.d.ts
types/options.d.ts

Allow `annotations` to be an object (as used in the current documentation) as well as an array (as used by older versions of the plugin).
Allow `id` property, as set by the object form of `annotations`.
Suppress ESLint warning; TypeScript declaration merging must exactly match the original, so ESLint's warning that the type is unused is a false positive.
Fix a typo in options.md.

Type fixes

---

docs/.vuepress/config.js
docs/samples/types/ellipse.md
src/types/ellipse.js

Add ellipse sample. Reordered the samples to be alphabetical. Removed the `true` (useFinalPosition) from `getCenterPoint` call so the animations are not jumpy.

Add ellipse sample

---

docs/guide/types/line.md
src/types/line.js
types/label.d.ts

PR implements `textAlign` option for line label in order to justify label content when there's more than one line.
Fixes #189

Enables textAlign option to line label

---

types/label.d.ts

The type definitions still used v0.x's `'top' | 'bottom' | 'left' | 'right' | 'center'`.
I noticed that LabelPosition is now identical to LabelTextAlign; however, they seem logically different, so keeping separate types made sense.

Update LabelPosition type to match v1.0.0

---

src/types/line.js

I found a couple of issues with the mouse event handling:
First, the isOnLabel logic didn't check whether the label was currently shown, so if a label had ever been draw in the past, its rectangle would continue to count for determining whether the mouse was on the line annotation.
Second, the logic I added for restricting mouse events to where the line actually is (#403) didn't work for horizontal or vertical lines.  For those, the denominator in interpolateY / interpolateX was 0, so the resulting value was infinity, which was clamped to 1; effectively, only the endpoint of the line could trigger a mouse enter event.

Fixes for line mouse events

---

types/options.d.ts

Hi, I can see `options.animations` being passed to `new Animations(chart, animOpts)` object here:
https://github.com/chartjs/chartjs-plugin-annotation/blob/v1.0.2/src/annotation.js#L140
(and I am actually using that option)
Animation:
https://github.com/chartjs/Chart.js/blob/a8337a3/types/animation.d.ts#L29
AnyObject:
https://github.com/chartjs/Chart.js/blob/a8337a32c976393e4648de633dcc49cdec2760b3/types/basic.d.ts#L2

Add missing animations prop to options interface.

---

docs/guide/interaction.md
src/events.js
types/events.d.ts

Currently the listeners on the annotations are receiving only the context.
I think it could be helpful to get also the event instance, separately, as additional argument.
A use case where to use the event could be to check if any modifier key is pressed in order to perform own logic only when a key is pressed.

Pass event instance to listeners

---

docs/guide/types/box.md
src/helpers.js
src/types/box.js
src/types/line.js
types/options.d.ts

- Add borderCapStyle and borderJoinStyle options to BoxAnnotation
- Move setBorderStyle function to the helpers, from line annotation, in order to be used by both BoxAnnotation and LineAnnotation label

Add borderCapStyle and borderJoinStyle options to BoxAnnotation

---

src/annotation.js
src/types/index.js

As the number of types grow, they deserve their own index.

Move annotation types handling to types/index.js

---

src/annotation.js
test/index.js
test/specs/annotation.spec.js

There was also an issue when unknow type was used in the object notation of annotations.
The options resolver fallback was undefined and it resulted in error. This fixes the fallback to use `line` as well.

Log warning when unknown annotation type is used

---

karma.conf.js
test/seed-reporter.js

Prints out the random seed used to run the test.
Can be used to reproduce failures locally by passing `?seed=number` to the browser.
> Chrome 96.0.4664.93 (Windows 10): Executed 322 of 322 SUCCESS (10.253 secs / 8.953 secs)
> Chrome 96.0.4664.93 (Windows 10): Randomized with seed 21107
> Chrome 96.0.4664.93 (Windows 10): Executed 109 of 322 (1 FAILED) (3.673 secs / 3.379 secs)                                                                                                                                                                                                                                      
> Chrome 96.0.4664.93 (Windows 10): Randomized with seed 94637

Add random seed reporting to test runs

---

docs/samples/box/disclosure.md

The disclosure box annotation sample is made responsive because, in reality, the disclosure text must have a font size which depends on the height of chart area.

Disclosure box sample is made responsive

---

.github/workflows/npmpublish.yml

The release process did not build the docs for latest/next and this makes them not functional.
I've fixed the current latest docs already manually (https://github.com/chartjs/chartjs-plugin-annotation/commit/ab6328d48730560845c817d773007ad6e6ba933c). This should fix the release process for next release.
Please note that the cloudflare caching takes some time to notice the fixed version.
Closes #565

Build docs before releasing as latest/next

---

.github/workflows/ci.yml
.github/workflows/documentation.yml
.github/workflows/npmpublish.yml
package-lock.json
package.json
test/integration/.eslintrc.yml
test/integration/integration-test.js
test/integration/ts/basic.ts
test/integration/ts/package.json
test/integration/ts/test.js
test/integration/ts/tsconfig.json
types/label.d.ts

Add integration tests against a set of typescript versions.
3.7 still worked, 3.6 failed on chart.js:
>Testing on typescript-3.6 ...
>node_modules/chart.js/types/index.esm.d.ts:461:5 - error TS2315: Type 'DeepPartial' is not generic.
This is adapted from https://github.com/graphql/graphql-js

Add integration tests (ts)

---

src/annotation.js
src/scale.js

This PR creates the scale module where there are some scale functions invoked from `annotation.js`.
These functions are NOT moved in a dedicated `helpers` or  in `helpers.chart` because they are invoked only from 1 point.
This is done to reduce the size of `annotation.js` and improving readability, concentrating all functions of the same topic in a dedicated module.

Move scale management functions to a dedicated file

---

src/annotation.js
src/types/box.js
src/types/ellipse.js
src/types/line.js
src/types/point.js
src/types/polygon.js

Sort default options alphabetically

---

src/annotation.js

Calculating the drawable elements once per chart update and storing them in the state, this PR is improving the performance of annotations drawing.

Store drawable elements to the state

---

docs/samples/box/basic.md
docs/samples/box/disclosure.md
docs/samples/box/quarters.md
docs/samples/charts/bar.md
docs/samples/charts/line.md
docs/samples/ellipse/basic.md
docs/samples/ellipse/rotation.md
docs/samples/intro.md
docs/samples/label/basic.md
docs/samples/label/callout.md
docs/samples/label/lowerUpper.md
docs/samples/label/point.md
docs/samples/line/animation.md
docs/samples/line/average.md
docs/samples/line/basic.md
docs/samples/line/labelVisibility.md
docs/samples/line/lowerUpper.md
docs/samples/line/standardDeviation.md
docs/samples/point/basic.md
docs/samples/polygon/basic.md
docs/samples/polygon/stop.md

This PR changes the samples where the actions were defined as `var`, instead of `const`.
it changes also the color definitions, where needed, adding a blank after the number

Change `var` to `const` in the samples

---

types/index.d.ts

New annotation types added to ElementOptionsByType to be able to set defaults in typescript with correct typings like:
```
import { defaults } from 'chart.js';
defaults.elements.labelAnnotation.font = {
color: '#999'
};
```

new annotation types added to ElementOptionsByType

---

test/specs/ellipse.spec.js

in FF the drawn chart is slightly different from Chrome.
This PR reduces the Y value for click event to stay in the rotated annotation

Fix event test case for rotated ellipse annotation

---

src/types/ellipse.js
src/types/line.js

All annotations are using `setBorderStyle` function to set the border options to canvas context.
This could be helpful for shadowing impl.

Normalize border style setting

---

src/types/ellipse.js
src/types/line.js

Remove `Math.PI`, using the `PI` constant of Chartjs helpers

Use PI constant of Chartjs helpers instead of Math.PI

---

src/types/line.js

As shared in #603, this PR adds JSDoc to `labelIsVisible` method of line annotation, in order to be aware about the optional arguments.

Add JSDoc to `labelIsVisible` method of line annotation

---

src/events.js

As shared in [PR 552](https://github.com/chartjs/chartjs-plugin-annotation/pull/552#discussion_r770655806) ,  we think its only confusing to rename the imports if not really needed.

Remove renaming the imports from chartjs.helpers of callback function

---

docs/guide/configuration.md
docs/guide/types/box.md
docs/guide/types/ellipse.md
docs/guide/types/label.md
docs/guide/types/line.md
docs/guide/types/polygon.md

Sort alphabetically the options definitions in the documentation.
As common practice, adds the dot at the end of the options description.

Sort alphabetically the options definitions in the documentation

---

docs/samples/label/point.md

The `point` node from label annotation sample because it is not valid anymore.

Remove `point` node from label annotation sample

---

docs/guide/types/box.md
docs/guide/types/line.md
docs/guide/types/polygon.md

This PR enables the link to label config in the guide menu, for box and line annotations.
It fixes also a typo in the doc

Enable the link to label configuration from the guide navigation menu

---

src/helpers/helpers.options.js

This PS is removing part of the code, currently not used because the function was taken by Chart.js (changing the default) but it had additional features not used in this plugin.

Remove `readValueToProps` function of options helpers

---

src/events.js
test/events.js
test/specs/events.spec.js

This PR is adding some additional test cases for event handling, in order to test specific condition in the code.
Furthermore it removes from `event.js` : 
1. a useless check on `state.annotations` because that instance can never be `undefined`. 
2. a if statement `if (!state.moveListened) {` because the `state.moveListened` could be always `false` to reach that code.

Improve event handling adding test cases

---

docs/guide/types/box.md
docs/guide/types/line.md

Fix the default values of the line and box options where they were wrong.

Fix the default options values in the documentation

---

src/types/label.js

This PR remove not used default route for `backgroundColor` option in label annotation

Remove not used default route for backgroundColor option in label annotation

---

test/index.js
test/specs/box.spec.js
test/utils.js

Essentially test the thing directly, instead of creating a chart and firing events and stuff. Coverage is the same, but some lines get less throughput:

Box: change event tests to inRange tests

---

test/specs/ellipse.spec.js
test/specs/point.spec.js

This PR remove events test cases with inRange method tests.

Point: change event tests to inRange tests

---

src/types/polygon.js
test/specs/polygon.spec.js

This PR remove events test cases with inRange method tests.
it also adds a further check in `inRange` of polygon because if the radius is set to zero, the point (element.x, element.y) is accepted.
The approach for polygon is a little bit different comparing with point because the polygon is calculating the point elements (used in `inRange`) at initialization of the element.

Polygon: change event tests to inRange tests

---

docs/guide/types/line.md

Fix `scaleId` versus `scaleID`, `xScaleId` versus `xScaleID`, `yScaleId` versus `yScaleID`.
Minor grammatical updates.

Documentation updates

---

src/scale.js
test/specs/annotation.spec.js

Fix #662
The warning message will be emitted on the console if the scaleID is missing and also if there is any options to locate the annotation (`x/yValue`, `x/yMin` and  `x/yMax`).

Update the warning logic for missing scale

---

src/annotation.js
src/elements.js

This PR creates the elements file where there are some elements functions invoked from annotation.js.
These functions are NOT moved in a dedicated helpers or in helpers.chart because they are invoked only from 1 point.
This is done to reduce the size of annotation.js and improving readability, concentrating all functions of the same topic in a dedicated file.

Move elements management functions to a dedicated file

---

.github/release-drafter.yml

Automatic PR to update dependencies are currently not managed in `release-draft`.
This PR adds `'dependencies'` label to `'Development'` section.

Add dependencies label of PR to development section in release note

---

docs/samples/point/combined.md

Fix point sample on combined annotations, resetting `borderDash` option.

Fix point sample on combined annotations

---

src/types/box.js

Remove the assignment of rotation in box annotation, used only once.

Remove the assignment used only once

---

src/helpers/helpers.core.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

docs/.vuepress/config.js
docs/guide/index.md
docs/guide/migrationV2.md

Add migration guide v2 section to getting started page

Add migration guide v2 section to getting started page

---

docs/guide/configuration.md
docs/guide/migrationV2.md
src/annotation.js
src/events.js
test/events.js
test/specs/events.spec.js
types/events.d.ts
types/options.d.ts

This PR is removing `dblclick` event hook. This is done in order to enable the chart redrawing from event hook, see issue #593.
To perform a double click, the plugin has to work in asynchronous way and this is a showstopper to enable the chart redrawing because the event hook should return `true` if redrawing is needed.

Remove dblclick hook to prepare chart redrawing from an event hook

---

docs/.vuepress/config.js
docs/samples/interaction.md

This PR is adding a specific sample where the user can check the different behaviors with different interaction options.
https://github.com/chartjs/chartjs-plugin-annotation/issues/718#issuecomment-1091725296

Add sample about interaction options

---

docs/guide/migrationV2.md
package-lock.json
package.json
src/annotation.js

Remove todo for V2.
Although not sure if we want it to be minimal 3.7 because of the bugfix or 3.8 if we want to remove this todo as wel:
https://github.com/chartjs/chartjs-plugin-annotation/blob/70078ccbe49568f6a4106667ad008bef7edf5495/src/helpers/helpers.canvas.js#L07-L18

Require at least chartjs v3.7

---

docs/guide/migrationV2.md
docs/samples/interaction.md
src/annotation.js
src/types/box.js
src/types/label.js
test/fixtures/box/label-dynamic.js
types/element.d.ts

This PR moves label node of box annotation to sub element.
This PR enables the box label animation.

Enable box annotation label as label sub-element

---

docs/guide/configuration.md
docs/guide/migrationV2.md
docs/samples/box/quarters.md
docs/samples/line/labelVisibility.md
docs/samples/line/limited.md
docs/samples/point/combined.md
docs/samples/point/outsideChartArea.md
docs/samples/polygon/outsideChartArea.md
types/options.d.ts
types/tests/exports.ts

Add documentation and type for 'common' plugin option

Add documentation and type for 'common' plugin option

---

docs/guide/configuration.md
src/annotation.js
types/options.d.ts
types/tests/exports.ts

The `interaction` object has been moved at top level of plugin options, instead of common object as implemented by PR #630.
This is because the `interaction` is not configurable at annotation instance but is a plugin configuration, like `clip` one.

Move interaction object at top level of plugin options

---

src/types/label.js

This reduces complexity using the enumerated callout position values to check if manageable instead of an if statement with for conditions in OR.

Reduce complexity for resolving the label callout position

---

docs/.vuepress/config.js
docs/guide/types/_commonOptions.md
docs/guide/types/box.md
docs/guide/types/ellipse.md
docs/guide/types/label.md
docs/guide/types/line.md
docs/guide/types/point.md
docs/guide/types/polygon.md
package-lock.json
package.json

This PR is adding `_commonOptions.md` file with all common annotation options, to include in each annotation type documentation.

Adds common annotation options section in the documentation

---

docs/.vuepress/config.js
docs/samples/interaction/dragging.md
docs/samples/interaction/selection.md

This PR is adding a sample to the doc to show how you can select an annotation.

Add sample how to select annotations

---

docs/guide/types/box.md
docs/guide/types/ellipse.md
docs/guide/types/label.md
docs/guide/types/line.md
docs/guide/types/point.md
docs/guide/types/polygon.md

Add element diagrams to the annotation types guide

Add element diagrams to the annotation types guide

---

docs/guide/configuration.md

Remove animation properties not used anymore from documentation

Remove animation properties from documentation, not used anymore

---

docs/guide/migrationV2.md
test/integration/ts/package.json
types/label.d.ts
types/options.d.ts
types/tests/exports.ts

This PR is changing the types definitions in order to:
- have all types on top of the file
- remove `AnnotationCoordinates` because adds the options in `CoreAnnotationOptions`
- remove `AnnotationPluginCommonOptions`  and changes `common` option defintion to accept a types annotation options
- reorder the options by their name, sorting alphabetically

Change and reorder the types definitions

---

src/types/label.js
src/types/line.js

Manage line label visibility when chart is zooming or panning

---

docs/guide/types/_commonOptions.md
docs/guide/types/box.md
docs/guide/types/ellipse.md
docs/guide/types/label.md
docs/guide/types/line.md
docs/guide/types/point.md
docs/guide/types/polygon.md

Add id option documentation to all annotations

---

src/annotation.js

With CHART.JS 4, PR https://github.com/chartjs/Chart.js/pull/10549, the `destroy` plugin hook has been removed and replaced with `afterDestroy`.
Currently, the version 2.1.0 is not cleaning the states map.

Remove destroy plugin hook and replaced with afterDestroy

---

docs/guide/types/label.md

Fix documentation about label annotation and its positioning

---

package.json

Should fix #83. @kurkle @LeeLenaleee can you confirm? My experience on packaging is not so huge.

Add exports to manage "import" and "require" inclusions

---

docs/guide/configuration.md
docs/guide/migrationV2.md
docs/guide/options.md
docs/guide/types/_commonInnerLabel.md
docs/guide/types/_commonOptions.md
docs/guide/types/box.md
docs/guide/types/ellipse.md
docs/guide/types/label.md
docs/guide/types/line.md
docs/guide/types/point.md
docs/guide/types/polygon.md
docs/guide/usage.md
docs/scripts/utils.js

Fix #818 
This PR is also removing the `autocolors` configuration plugin from the guide.

Fix links with anchors adding md extension in the documentation

---

src/events.js
src/helpers/helpers.options.js
src/hooks.js
src/scale.js

This PR is removing internal checks if an instance is a function using the Chart.js herlper

Use isFunction helper of Chart.js instead of internal check

---

docs/.vuepress/config.js
docs/samples/box/gradient.md

Add sample using gradient created by element dimension

---

karma.conf.js

See https://github.com/chartjs/chartjs-plugin-annotation/pull/856.
Firefox 110 added the following feature: **GPU-accelerated Canvas2D is enabled by default on macOS and Linux**.
It seems that this is breaking the test cases on fixtures.
This PR is trying to disable it.

Disable canvas acceleration in Firefox 110 in test cases

---

docs/samples/point/initAnim.md

Remove label node from point annotations, because not managed by poitns, from init samples.

Remove label node from point annotations from init samples

---

src/elements.js

The PR https://github.com/chartjs/chartjs-plugin-annotation/pull/801 introduced indexable options (`font` and `color`).
The current options resolution is checking if the options is indexable and if true, it stores the value of the options.
https://github.com/chartjs/chartjs-plugin-annotation/blob/bc38d6bfad27a052c199604e89d1338c07681d3f/src/elements.js#L134
In this way, it stores a `Proxy` object (or an array of `Proxy`) in element options, something that probably you don't want.
This PR is storing "plain" objects as `element.options`.

Fix value stored in element options for indexable option

---

types/index.d.ts

Fix compile errors when using multiple plugins

---

docs/.vuepress/config.ts

This Pr should fix the issue related to the documentation where the chart instances are not available because the chart.js elements are not registered.
The issue sounds to be related to `vuepress-theme-chartjs` and how imports are managed. 
Not clear to me why (apologize) but adding the import names where missing, the app built by webpack/vue seems to have the registration and is importing everything as it should.

Fix documentation after setting plugin as module

---

docs/guide/integration.md

There is no `chart.min.js` file when you `npm install chart.js`. I supposed it has been replaced by `chart.umd.js` as indicated in the [Chart.js integration documentation](https://www.chartjs.org/docs/latest/getting-started/integration.html).

Replace chart.min.js by chart.umd.js
